cc_library(
    name = "cubli",
    srcs = ["cubli.h",
            "cubli.cpp",
            "cubli_state.h",
            "cubli_state.cpp",
            "cubli_geometry.h",
            "cubli_planning.h",
            "cubli_planning.cpp",],
    visibility = ["//visibility:public"],
    deps = ["//third-party:rbdl",
            "//math:math"]
)