cc_library(
    name = "math",
    srcs = ["Pose.h",
            "Pose.cpp",
            "Frame.h",
            "Point.h",
            "Point.cpp"],
    visibility = ["//visibility:public"],
    deps = ["//third-party:rbdl"]
)