cc_test(
    name = "cubli_test",
    size = "small",
    srcs = ["test_cubli.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//cubli:cubli",
        "//math:math",
        "//third-party:rbdl",
    ],
)