cc_test(
    name = "pose_test",
    size = "small",
    srcs = ["test_pose.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//math:math",
    ],
)

cc_test(
    name = "frame_transform_test",
    size = "small",
    srcs = ["test_frame_transform.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//math:math",
    ],
)